### ISSUE TITLE
Issues when the view is loading, about rendering

### ISSUE THREAD

**Issue by zamarproject** [protonemedia/laravel-splade#361] opened 2023-03-21 17:45 UTC
- Laravel Version: 10.4.1
- PHP Version: 8.2.3
- Splade JS Version (npm): 1.4.4
- Splade PHP Version (composer): 1.4.4
- Dev environment (OS, Sail/Valet/etc): ...
  Mac OS Big Sur, 
You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```

Make sure both Splade packages (JS + PHP) are up-to-date and on the same version. For example, when using version 0.5.0 of the PHP package, you should use the same JavaScript package version.

### Description:

Seems to be that after making a fresh Laravel install, then installing Splade either in the 3 versions: 
Splade-Breeze,  Splade-JetStrean, and Splade just in Laravel,

There is an issue every time that the page or some view is loading, having a bad rendering.
As you could see in the video.

### Steps To Reproduce Issue:

In every of these videos, I´m refreshing the view, either refreshing directly the page in the browser and also every time that I save the view.

This issue, doesn´t happen in Breeze, JetStream, alone, without Splade. 

https://user-images.githubusercontent.com/87920475/226695961-5e82b031-fdee-49b7-b506-c4a9c43b33c9.mov

https://user-images.githubusercontent.com/87920475/226695977-52ec9cb0-9071-4fc6-8682-382cb8b9e091.mov

https://user-images.githubusercontent.com/87920475/226695997-1e78822d-f0e6-4993-a19d-b2e42c4d6205.mov

**Comment by rusdyahmad** [comment] 2023-03-22 01:10
This is because you are running

`npm run dev`

to get latest js & css files run

`npm run build`

**Comment by ifathurrohman** [comment] 2023-03-25 09:15
While you are coding during the development process using Vite (npm run dev), this will always happen because Vite behind the scenes always refreshes the page when changes occur. But when the development process is complete and you run npm run build (you are no longer using Vite), that won't happen.

**Comment by pascalbaljet** [comment] 2023-03-30 21:42
Duplicate of #146

**Closed by pascalbaljet** 2023-03-30 21:42 UTC
